# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backtrack.ui',
# licensing of 'backtrack.ui' applies.
#
# Created: Wed Dec 11 15:06:22 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(906, 548)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.deal_pattern_label = QtWidgets.QLabel(Form)
        self.deal_pattern_label.setObjectName("deal_pattern_label")
        self.gridLayout.addWidget(self.deal_pattern_label, 0, 2, 1, 1)
        self.close_commission = QtWidgets.QLineEdit(Form)
        self.close_commission.setObjectName("close_commission")
        self.gridLayout.addWidget(self.close_commission, 4, 1, 1, 1)
        self.slippage_buy_label = QtWidgets.QLabel(Form)
        self.slippage_buy_label.setObjectName("slippage_buy_label")
        self.gridLayout.addWidget(self.slippage_buy_label, 5, 2, 1, 1)
        self.run_btn = QtWidgets.QPushButton(Form)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 8, 3, 1, 1)
        self.initial_capital_label = QtWidgets.QLabel(Form)
        self.initial_capital_label.setObjectName("initial_capital_label")
        self.gridLayout.addWidget(self.initial_capital_label, 0, 0, 1, 1)
        self.close_pattern_label = QtWidgets.QLabel(Form)
        self.close_pattern_label.setObjectName("close_pattern_label")
        self.gridLayout.addWidget(self.close_pattern_label, 1, 2, 1, 1)
        self.slippage_sell = QtWidgets.QSpinBox(Form)
        self.slippage_sell.setObjectName("slippage_sell")
        self.gridLayout.addWidget(self.slippage_sell, 3, 3, 1, 1)
        self.add_data_btn = QtWidgets.QPushButton(Form)
        self.add_data_btn.setObjectName("add_data_btn")
        self.gridLayout.addWidget(self.add_data_btn, 7, 0, 1, 1)
        self.commission_label = QtWidgets.QLabel(Form)
        self.commission_label.setObjectName("commission_label")
        self.gridLayout.addWidget(self.commission_label, 3, 0, 1, 1)
        self.slippage_sell_label = QtWidgets.QLabel(Form)
        self.slippage_sell_label.setObjectName("slippage_sell_label")
        self.gridLayout.addWidget(self.slippage_sell_label, 3, 2, 1, 1)
        self.data_label = QtWidgets.QLabel(Form)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.gridLayout.addWidget(self.data_label, 7, 1, 1, 2)
        self.slippage_buy = QtWidgets.QSpinBox(Form)
        self.slippage_buy.setObjectName("slippage_buy")
        self.gridLayout.addWidget(self.slippage_buy, 5, 3, 1, 1)
        self.commission = QtWidgets.QLineEdit(Form)
        self.commission.setObjectName("commission")
        self.gridLayout.addWidget(self.commission, 3, 1, 1, 1)
        self.size_map = QtWidgets.QSpinBox(Form)
        self.size_map.setProperty("value", 15)
        self.size_map.setObjectName("size_map")
        self.gridLayout.addWidget(self.size_map, 1, 1, 1, 1)
        self.today_commission = QtWidgets.QLineEdit(Form)
        self.today_commission.setObjectName("today_commission")
        self.gridLayout.addWidget(self.today_commission, 5, 1, 1, 1)
        self.close_pattern = QtWidgets.QComboBox(Form)
        self.close_pattern.setEditable(True)
        self.close_pattern.setObjectName("close_pattern")
        self.close_pattern.addItem("")
        self.gridLayout.addWidget(self.close_pattern, 1, 3, 1, 1)
        self.slippage_cover_label = QtWidgets.QLabel(Form)
        self.slippage_cover_label.setObjectName("slippage_cover_label")
        self.gridLayout.addWidget(self.slippage_cover_label, 4, 2, 1, 1)
        self.local_symbol_box = QtWidgets.QComboBox(Form)
        self.local_symbol_box.setEditable(True)
        self.local_symbol_box.setObjectName("local_symbol_box")
        self.gridLayout.addWidget(self.local_symbol_box, 7, 3, 1, 1)
        self.slippage_short_label = QtWidgets.QLabel(Form)
        self.slippage_short_label.setObjectName("slippage_short_label")
        self.gridLayout.addWidget(self.slippage_short_label, 6, 2, 1, 1)
        self.slippage_cover = QtWidgets.QSpinBox(Form)
        self.slippage_cover.setObjectName("slippage_cover")
        self.gridLayout.addWidget(self.slippage_cover, 4, 3, 1, 1)
        self.add_backtrack_btn = QtWidgets.QPushButton(Form)
        self.add_backtrack_btn.setObjectName("add_backtrack_btn")
        self.gridLayout.addWidget(self.add_backtrack_btn, 8, 0, 1, 1)
        self.initial_capital = QtWidgets.QSpinBox(Form)
        self.initial_capital.setMaximum(999999999)
        self.initial_capital.setProperty("value", 100000)
        self.initial_capital.setObjectName("initial_capital")
        self.gridLayout.addWidget(self.initial_capital, 0, 1, 1, 1)
        self.close_commission_label = QtWidgets.QLabel(Form)
        self.close_commission_label.setObjectName("close_commission_label")
        self.gridLayout.addWidget(self.close_commission_label, 4, 0, 1, 1)
        self.yesterday_commission = QtWidgets.QLineEdit(Form)
        self.yesterday_commission.setObjectName("yesterday_commission")
        self.gridLayout.addWidget(self.yesterday_commission, 6, 1, 1, 1)
        self.size_map_label = QtWidgets.QLabel(Form)
        self.size_map_label.setObjectName("size_map_label")
        self.gridLayout.addWidget(self.size_map_label, 1, 0, 1, 1)
        self.yesterday_commission_label = QtWidgets.QLabel(Form)
        self.yesterday_commission_label.setObjectName("yesterday_commission_label")
        self.gridLayout.addWidget(self.yesterday_commission_label, 6, 0, 1, 1)
        self.slippage_short = QtWidgets.QSpinBox(Form)
        self.slippage_short.setObjectName("slippage_short")
        self.gridLayout.addWidget(self.slippage_short, 6, 3, 1, 1)
        self.deal_pattern = QtWidgets.QComboBox(Form)
        self.deal_pattern.setEditable(True)
        self.deal_pattern.setObjectName("deal_pattern")
        self.deal_pattern.addItem("")
        self.gridLayout.addWidget(self.deal_pattern, 0, 3, 1, 1)
        self.today_commission_label = QtWidgets.QLabel(Form)
        self.today_commission_label.setObjectName("today_commission_label")
        self.gridLayout.addWidget(self.today_commission_label, 5, 0, 1, 1)
        self.backtrack_label = QtWidgets.QLabel(Form)
        self.backtrack_label.setAlignment(QtCore.Qt.AlignCenter)
        self.backtrack_label.setObjectName("backtrack_label")
        self.gridLayout.addWidget(self.backtrack_label, 8, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setColumnStretch(3, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "回测结果", None, -1))

        self.deal_pattern_label.setText(QtWidgets.QApplication.translate("Form", "deal_pattern", None, -1))
        self.close_commission.setText(QtWidgets.QApplication.translate("Form", "0.005", None, -1))
        self.slippage_buy_label.setText(QtWidgets.QApplication.translate("Form", "slippage_buy", None, -1))
        self.run_btn.setText(QtWidgets.QApplication.translate("Form", "🚀 Run", None, -1))
        self.initial_capital_label.setText(QtWidgets.QApplication.translate("Form", "initial_capital", None, -1))
        self.close_pattern_label.setText(QtWidgets.QApplication.translate("Form", "close_pattern", None, -1))
        self.add_data_btn.setText(QtWidgets.QApplication.translate("Form", "添加数据", None, -1))
        self.commission_label.setText(QtWidgets.QApplication.translate("Form", "commission", None, -1))
        self.slippage_sell_label.setText(QtWidgets.QApplication.translate("Form", "slippage_sell", None, -1))
        self.data_label.setText(QtWidgets.QApplication.translate("Form", "空", None, -1))
        self.commission.setText(QtWidgets.QApplication.translate("Form", "0.005", None, -1))
        self.today_commission.setText(QtWidgets.QApplication.translate("Form", "0.005", None, -1))
        self.close_pattern.setItemText(0, QtWidgets.QApplication.translate("Form", "yesterday", None, -1))
        self.slippage_cover_label.setText(QtWidgets.QApplication.translate("Form", "slippage_cover", None, -1))
        self.slippage_short_label.setText(QtWidgets.QApplication.translate("Form", "slippage_short", None, -1))
        self.add_backtrack_btn.setText(QtWidgets.QApplication.translate("Form", "回测API", None, -1))
        self.close_commission_label.setText(QtWidgets.QApplication.translate("Form", "close_commission", None, -1))
        self.yesterday_commission.setText(QtWidgets.QApplication.translate("Form", "0.002", None, -1))
        self.size_map_label.setText(QtWidgets.QApplication.translate("Form", "size_map", None, -1))
        self.yesterday_commission_label.setText(QtWidgets.QApplication.translate("Form", "yesterday_commission", None, -1))
        self.deal_pattern.setItemText(0, QtWidgets.QApplication.translate("Form", "price", None, -1))
        self.today_commission_label.setText(QtWidgets.QApplication.translate("Form", "today_commission", None, -1))
        self.backtrack_label.setText(QtWidgets.QApplication.translate("Form", "空", None, -1))

