# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backtrack.ui',
# licensing of 'backtrack.ui' applies.
#
# Created: Tue Dec 10 12:03:58 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(796, 491)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.initial_capital = QtWidgets.QSpinBox(Form)
        self.initial_capital.setMaximum(999999999)
        self.initial_capital.setProperty("value", 100000)
        self.initial_capital.setObjectName("initial_capital")
        self.gridLayout.addWidget(self.initial_capital, 0, 1, 1, 1)
        self.add_backtrack_btn = QtWidgets.QPushButton(Form)
        self.add_backtrack_btn.setObjectName("add_backtrack_btn")
        self.gridLayout.addWidget(self.add_backtrack_btn, 8, 0, 1, 1)
        self.commission = QtWidgets.QLineEdit(Form)
        self.commission.setObjectName("commission")
        self.gridLayout.addWidget(self.commission, 3, 1, 1, 1)
        self.today_commission = QtWidgets.QLineEdit(Form)
        self.today_commission.setObjectName("today_commission")
        self.gridLayout.addWidget(self.today_commission, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.size_map = QtWidgets.QSpinBox(Form)
        self.size_map.setProperty("value", 15)
        self.size_map.setObjectName("size_map")
        self.gridLayout.addWidget(self.size_map, 1, 1, 1, 1)
        self.deal_pattern = QtWidgets.QComboBox(Form)
        self.deal_pattern.setEditable(True)
        self.deal_pattern.setObjectName("deal_pattern")
        self.deal_pattern.addItem("")
        self.gridLayout.addWidget(self.deal_pattern, 0, 3, 1, 1)
        self.close_pattern = QtWidgets.QComboBox(Form)
        self.close_pattern.setEditable(True)
        self.close_pattern.setObjectName("close_pattern")
        self.close_pattern.addItem("")
        self.gridLayout.addWidget(self.close_pattern, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.add_data_btn = QtWidgets.QPushButton(Form)
        self.add_data_btn.setObjectName("add_data_btn")
        self.gridLayout.addWidget(self.add_data_btn, 7, 0, 1, 1)
        self.slippage_sell = QtWidgets.QSpinBox(Form)
        self.slippage_sell.setObjectName("slippage_sell")
        self.gridLayout.addWidget(self.slippage_sell, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.close_commission = QtWidgets.QLineEdit(Form)
        self.close_commission.setObjectName("close_commission")
        self.gridLayout.addWidget(self.close_commission, 4, 1, 1, 1)
        self.run_btn = QtWidgets.QPushButton(Form)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 8, 3, 1, 1)
        self.data_label = QtWidgets.QLabel(Form)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.gridLayout.addWidget(self.data_label, 7, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.slippage_buy = QtWidgets.QSpinBox(Form)
        self.slippage_buy.setObjectName("slippage_buy")
        self.gridLayout.addWidget(self.slippage_buy, 5, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 2, 1, 1)
        self.local_symbol_box = QtWidgets.QComboBox(Form)
        self.local_symbol_box.setEditable(True)
        self.local_symbol_box.setObjectName("local_symbol_box")
        self.gridLayout.addWidget(self.local_symbol_box, 7, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.slippage_cover = QtWidgets.QSpinBox(Form)
        self.slippage_cover.setObjectName("slippage_cover")
        self.gridLayout.addWidget(self.slippage_cover, 4, 3, 1, 1)
        self.yesterday_commission = QtWidgets.QLineEdit(Form)
        self.yesterday_commission.setObjectName("yesterday_commission")
        self.gridLayout.addWidget(self.yesterday_commission, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.slippage_short = QtWidgets.QSpinBox(Form)
        self.slippage_short.setObjectName("slippage_short")
        self.gridLayout.addWidget(self.slippage_short, 6, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.backtrack_label = QtWidgets.QLabel(Form)
        self.backtrack_label.setAlignment(QtCore.Qt.AlignCenter)
        self.backtrack_label.setObjectName("backtrack_label")
        self.gridLayout.addWidget(self.backtrack_label, 8, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.res_layout = QtWidgets.QHBoxLayout()
        self.res_layout.setObjectName("res_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.res_layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.res_layout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.add_backtrack_btn.setText(QtWidgets.QApplication.translate("Form", "回测API", None, -1))
        self.commission.setText(QtWidgets.QApplication.translate("Form", "0.005", None, -1))
        self.today_commission.setText(QtWidgets.QApplication.translate("Form", "0.005", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "slippage_sell", None, -1))
        self.deal_pattern.setItemText(0, QtWidgets.QApplication.translate("Form", "price", None, -1))
        self.close_pattern.setItemText(0, QtWidgets.QApplication.translate("Form", "yesterday", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "slippage_short", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "close_commission", None, -1))
        self.add_data_btn.setText(QtWidgets.QApplication.translate("Form", "添加数据", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "deal_pattern", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "yesterday_commission", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "slippage_cover", None, -1))
        self.close_commission.setText(QtWidgets.QApplication.translate("Form", "0.005", None, -1))
        self.run_btn.setText(QtWidgets.QApplication.translate("Form", "Run", None, -1))
        self.data_label.setText(QtWidgets.QApplication.translate("Form", "空", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "commission", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "slippage_buy", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "today_commission", None, -1))
        self.yesterday_commission.setText(QtWidgets.QApplication.translate("Form", "0.002", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "size_map", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "initial_capital", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "close_pattern", None, -1))
        self.backtrack_label.setText(QtWidgets.QApplication.translate("Form", "空", None, -1))

