# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui',
# licensing of 'config.ui' applies.
#
# Created: Sun Dec  8 16:08:48 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(563, 374)
        Config.setMinimumSize(QtCore.QSize(563, 374))
        Config.setMaximumSize(QtCore.QSize(563, 374))
        font = QtGui.QFont()
        font.setPointSize(13)
        Config.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu/images/bee_temp_grey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Config.setWindowIcon(icon)
        self.formLayout_2 = QtWidgets.QFormLayout(Config)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Config)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Config)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Config)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Config)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Config)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Config)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(Config)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(Config)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.INSTRUMENT_INDEPEND = QtWidgets.QCheckBox(Config)
        self.INSTRUMENT_INDEPEND.setText("")
        self.INSTRUMENT_INDEPEND.setObjectName("INSTRUMENT_INDEPEND")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.INSTRUMENT_INDEPEND)
        self.SLIPPAGE_SHORT = QtWidgets.QSpinBox(Config)
        self.SLIPPAGE_SHORT.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SLIPPAGE_SHORT.setMinimum(-999)
        self.SLIPPAGE_SHORT.setMaximum(999)
        self.SLIPPAGE_SHORT.setObjectName("SLIPPAGE_SHORT")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SLIPPAGE_SHORT)
        self.SLIPPAGE_BUY = QtWidgets.QSpinBox(Config)
        self.SLIPPAGE_BUY.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SLIPPAGE_BUY.setMinimum(-999)
        self.SLIPPAGE_BUY.setMaximum(999)
        self.SLIPPAGE_BUY.setObjectName("SLIPPAGE_BUY")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SLIPPAGE_BUY)
        self.SLIPPAGE_COVER = QtWidgets.QSpinBox(Config)
        self.SLIPPAGE_COVER.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SLIPPAGE_COVER.setMinimum(-999)
        self.SLIPPAGE_COVER.setMaximum(999)
        self.SLIPPAGE_COVER.setObjectName("SLIPPAGE_COVER")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SLIPPAGE_COVER)
        self.SLIPPAGE_SELL = QtWidgets.QSpinBox(Config)
        self.SLIPPAGE_SELL.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SLIPPAGE_SELL.setMinimum(-999)
        self.SLIPPAGE_SELL.setMaximum(999)
        self.SLIPPAGE_SELL.setObjectName("SLIPPAGE_SELL")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SLIPPAGE_SELL)
        self.CLOSE_PATTERN = QtWidgets.QComboBox(Config)
        self.CLOSE_PATTERN.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CLOSE_PATTERN.setObjectName("CLOSE_PATTERN")
        self.CLOSE_PATTERN.addItem("")
        self.CLOSE_PATTERN.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.CLOSE_PATTERN)
        self.SHARED_FUNC = QtWidgets.QCheckBox(Config)
        self.SHARED_FUNC.setText("")
        self.SHARED_FUNC.setObjectName("SHARED_FUNC")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.SHARED_FUNC)
        self.REFRESH_INTERVAL = QtWidgets.QDoubleSpinBox(Config)
        self.REFRESH_INTERVAL.setMaximumSize(QtCore.QSize(200, 16777215))
        self.REFRESH_INTERVAL.setObjectName("REFRESH_INTERVAL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.REFRESH_INTERVAL)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.submit_btn = QtWidgets.QPushButton(Config)
        self.submit_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.submit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout.addWidget(self.submit_btn)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.line = QtWidgets.QFrame(Config)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        Config.setWindowTitle(QtWidgets.QApplication.translate("Config", "配置", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Config", "REFRESH_INTERVAL/定时刷新秒数", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Config", "INSTRUMENT_INDEPEND/是否开启独立行情", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Config", "SLIPPAGE_SHORT/卖空滑点", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Config", "SLIPPAGE_BUY/买多滑点", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Config", "SLIPPAGE_COVER/平多头滑点", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Config", "SLIPPAGE_SELL/平空头滑点", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Config", "CLOSE_PATTERN/指定优先平今或者平昨", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Config", "SHARED_FUNC/分时图数据", None, -1))
        self.CLOSE_PATTERN.setItemText(0, QtWidgets.QApplication.translate("Config", "today", None, -1))
        self.CLOSE_PATTERN.setItemText(1, QtWidgets.QApplication.translate("Config", "yesterday", None, -1))
        self.submit_btn.setText(QtWidgets.QApplication.translate("Config", "提交更改", None, -1))

import app.resource.mainwindow_rc
