# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui',
# licensing of 'order.ui' applies.
#
# Created: Mon Nov 11 15:33:37 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Order(object):
    def setupUi(self, Order):
        Order.setObjectName("Order")
        Order.resize(1748, 899)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(Order.sizePolicy().hasHeightForWidth())
        Order.setSizePolicy(sizePolicy)
        Order.setMinimumSize(QtCore.QSize(0, 0))
        self.formLayout_2 = QtWidgets.QFormLayout(Order)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tick_table = QtWidgets.QTableWidget(Order)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.tick_table.sizePolicy().hasHeightForWidth())
        self.tick_table.setSizePolicy(sizePolicy)
        self.tick_table.setMinimumSize(QtCore.QSize(400, 0))
        self.tick_table.setMaximumSize(QtCore.QSize(500, 500))
        self.tick_table.setObjectName("tick_table")
        self.tick_table.setColumnCount(2)
        self.tick_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tick_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tick_table.setHorizontalHeaderItem(1, item)
        self.tick_table.verticalHeader().setSortIndicatorShown(True)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tick_table)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.kline_layout = QtWidgets.QVBoxLayout()
        self.kline_layout.setObjectName("kline_layout")
        self.horizontalLayout_4.addLayout(self.kline_layout)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalWidget = QtWidgets.QWidget(Order)
        self.verticalWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.log_list = QtWidgets.QListWidget(self.verticalWidget)
        self.log_list.setObjectName("log_list")
        self.verticalLayout_2.addWidget(self.log_list)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.verticalWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Order)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.position_tab = QtWidgets.QWidget()
        self.position_tab.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.position_tab.setObjectName("position_tab")
        self.position_table = QtWidgets.QTableWidget(self.position_tab)
        self.position_table.setGeometry(QtCore.QRect(0, 0, 1000, 331))
        self.position_table.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.position_table.setObjectName("position_table")
        self.position_table.setColumnCount(8)
        self.position_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(7, item)
        self.tabWidget.addTab(self.position_tab, "")
        self.active_order_tab = QtWidgets.QWidget()
        self.active_order_tab.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.active_order_tab.setObjectName("active_order_tab")
        self.activate_order_table = QtWidgets.QTableWidget(self.active_order_tab)
        self.activate_order_table.setGeometry(QtCore.QRect(0, 0, 1000, 331))
        self.activate_order_table.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.activate_order_table.setObjectName("activate_order_table")
        self.activate_order_table.setColumnCount(10)
        self.activate_order_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(9, item)
        self.tabWidget.addTab(self.active_order_tab, "")
        self.order_tab = QtWidgets.QWidget()
        self.order_tab.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.order_tab.setObjectName("order_tab")
        self.order_table = QtWidgets.QTableWidget(self.order_tab)
        self.order_table.setGeometry(QtCore.QRect(0, 0, 1000, 331))
        self.order_table.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.order_table.setObjectName("order_table")
        self.order_table.setColumnCount(8)
        self.order_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(7, item)
        self.tabWidget.addTab(self.order_tab, "")
        self.trade_tab = QtWidgets.QWidget()
        self.trade_tab.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.trade_tab.setObjectName("trade_tab")
        self.trade_table = QtWidgets.QTableWidget(self.trade_tab)
        self.trade_table.setGeometry(QtCore.QRect(0, 0, 1000, 321))
        self.trade_table.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.trade_table.setObjectName("trade_table")
        self.trade_table.setColumnCount(7)
        self.trade_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.trade_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.widget = QtWidgets.QWidget(Order)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.local_symbol_zn = QtWidgets.QLabel(self.widget)
        self.local_symbol_zn.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 75 24pt \"Arial\";")
        self.local_symbol_zn.setText("")
        self.local_symbol_zn.setObjectName("local_symbol_zn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.local_symbol_zn)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.symbol_name_list = QtWidgets.QComboBox(self.widget)
        self.symbol_name_list.setEditable(True)
        self.symbol_name_list.setObjectName("symbol_name_list")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.symbol_name_list)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.price_type = QtWidgets.QComboBox(self.widget)
        self.price_type.setObjectName("price_type")
        self.price_type.addItem("")
        self.price_type.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price_type)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.price = QtWidgets.QDoubleSpinBox(self.widget)
        self.price.setMaximum(9999999.0)
        self.price.setObjectName("price")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.price)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.volume = QtWidgets.QSpinBox(self.widget)
        self.volume.setMinimum(1)
        self.volume.setMaximum(9999999)
        self.volume.setObjectName("volume")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.volume)
        self.buy_btn = QtWidgets.QPushButton(self.widget)
        self.buy_btn.setObjectName("buy_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.buy_btn)
        self.short_btn = QtWidgets.QPushButton(self.widget)
        self.short_btn.setObjectName("short_btn")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.short_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(40, 0))
        self.label_8.setStyleSheet("image: url(:/menu/icon/下单.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.horizontalLayout_2.addWidget(self.widget)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.retranslateUi(Order)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Order)

    def retranslateUi(self, Order):
        Order.setWindowTitle(QtWidgets.QApplication.translate("Order", "Form", None, -1))
        self.tick_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "key", None, -1))
        self.tick_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "value", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Order", "日志信息", None, -1))
        self.position_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "持仓合约", None, -1))
        self.position_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "持仓方向", None, -1))
        self.position_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.position_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "持仓手数", None, -1))
        self.position_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "浮动盈亏", None, -1))
        self.position_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "持仓均价", None, -1))
        self.position_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "昨日持仓手数", None, -1))
        self.position_table.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Order", "操作", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.position_tab), QtWidgets.QApplication.translate("Order", "持仓数据", None, -1))
        self.activate_order_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "id", None, -1))
        self.activate_order_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "报单合约", None, -1))
        self.activate_order_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "报单方向", None, -1))
        self.activate_order_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.activate_order_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "报单手数", None, -1))
        self.activate_order_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "报单价格", None, -1))
        self.activate_order_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "状态", None, -1))
        self.activate_order_table.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Order", "报单时间", None, -1))
        self.activate_order_table.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("Order", "报单类型", None, -1))
        self.activate_order_table.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("Order", "操作", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.active_order_tab), QtWidgets.QApplication.translate("Order", "待成交数据", None, -1))
        self.order_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "报单合约", None, -1))
        self.order_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "报单方向", None, -1))
        self.order_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.order_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "报单手数", None, -1))
        self.order_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "报单价格", None, -1))
        self.order_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "状态", None, -1))
        self.order_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "时间", None, -1))
        self.order_table.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Order", "价格类型", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.order_tab), QtWidgets.QApplication.translate("Order", "发单数据", None, -1))
        self.trade_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "成交合约", None, -1))
        self.trade_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "成交方向", None, -1))
        self.trade_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.trade_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "报单手数", None, -1))
        self.trade_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "报单价格", None, -1))
        self.trade_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "开平", None, -1))
        self.trade_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "成交时间", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trade_tab), QtWidgets.QApplication.translate("Order", "成交数据", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Order", "中文名", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Order", "合约", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Order", "类型", None, -1))
        self.price_type.setItemText(0, QtWidgets.QApplication.translate("Order", "限价", None, -1))
        self.price_type.setItemText(1, QtWidgets.QApplication.translate("Order", "市价", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Order", "价格", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Order", "手数", None, -1))
        self.buy_btn.setText(QtWidgets.QApplication.translate("Order", "买多", None, -1))
        self.short_btn.setText(QtWidgets.QApplication.translate("Order", "卖空", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Order", "下单", None, -1))

import app.resource.mainwindow_rc
