# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui',
# licensing of 'order.ui' applies.
#
# Created: Mon Dec 23 19:47:12 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Order(object):
    def setupUi(self, Order):
        Order.setObjectName("Order")
        Order.resize(799, 364)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(Order.sizePolicy().hasHeightForWidth())
        Order.setSizePolicy(sizePolicy)
        Order.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu/images/bee_temp_grey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Order.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Order)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.account_label = QtWidgets.QLabel(Order)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.account_label.setFont(font)
        self.account_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.account_label.setObjectName("account_label")
        self.horizontalLayout_3.addWidget(self.account_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(Order)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Order)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.position_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_tab.sizePolicy().hasHeightForWidth())
        self.position_tab.setSizePolicy(sizePolicy)
        self.position_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.position_tab.setObjectName("position_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.position_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.position_table = QtWidgets.QTableWidget(self.position_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_table.sizePolicy().hasHeightForWidth())
        self.position_table.setSizePolicy(sizePolicy)
        self.position_table.setMinimumSize(QtCore.QSize(0, 0))
        self.position_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.position_table.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.position_table.setLineWidth(1)
        self.position_table.setObjectName("position_table")
        self.position_table.setColumnCount(8)
        self.position_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.position_table.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.position_table)
        self.tabWidget.addTab(self.position_tab, "")
        self.active_order_tab = QtWidgets.QWidget()
        self.active_order_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.active_order_tab.setObjectName("active_order_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.active_order_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.activate_order_table = QtWidgets.QTableWidget(self.active_order_tab)
        self.activate_order_table.setMinimumSize(QtCore.QSize(0, 0))
        self.activate_order_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.activate_order_table.setObjectName("activate_order_table")
        self.activate_order_table.setColumnCount(10)
        self.activate_order_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.activate_order_table.setHorizontalHeaderItem(9, item)
        self.verticalLayout_3.addWidget(self.activate_order_table)
        self.tabWidget.addTab(self.active_order_tab, "")
        self.order_tab = QtWidgets.QWidget()
        self.order_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.order_tab.setObjectName("order_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.order_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.order_table = QtWidgets.QTableWidget(self.order_tab)
        self.order_table.setMinimumSize(QtCore.QSize(0, 0))
        self.order_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.order_table.setObjectName("order_table")
        self.order_table.setColumnCount(8)
        self.order_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(7, item)
        self.verticalLayout_4.addWidget(self.order_table)
        self.tabWidget.addTab(self.order_tab, "")
        self.trade_tab = QtWidgets.QWidget()
        self.trade_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trade_tab.setObjectName("trade_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.trade_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.trade_table = QtWidgets.QTableWidget(self.trade_tab)
        self.trade_table.setMinimumSize(QtCore.QSize(0, 0))
        self.trade_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trade_table.setObjectName("trade_table")
        self.trade_table.setColumnCount(7)
        self.trade_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trade_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_5.addWidget(self.trade_table)
        self.tabWidget.addTab(self.trade_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.widget = QtWidgets.QWidget(Order)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.widget.setFont(font)
        self.widget.setStyleSheet("font: 75 12pt \"Arial\";")
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.local_symbol_zn = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.local_symbol_zn.setFont(font)
        self.local_symbol_zn.setText("")
        self.local_symbol_zn.setAlignment(QtCore.Qt.AlignCenter)
        self.local_symbol_zn.setObjectName("local_symbol_zn")
        self.horizontalLayout_4.addWidget(self.local_symbol_zn)
        self.horizontalLayout_4.setStretch(1, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.symbol_name_list = QtWidgets.QComboBox(self.widget)
        self.symbol_name_list.setEditable(True)
        self.symbol_name_list.setObjectName("symbol_name_list")
        self.horizontalLayout_5.addWidget(self.symbol_name_list)
        self.horizontalLayout_5.setStretch(1, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.price_type = QtWidgets.QComboBox(self.widget)
        self.price_type.setObjectName("price_type")
        self.price_type.addItem("")
        self.price_type.addItem("")
        self.horizontalLayout_6.addWidget(self.price_type)
        self.horizontalLayout_6.setStretch(1, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.price = QtWidgets.QDoubleSpinBox(self.widget)
        self.price.setMaximum(9999999.0)
        self.price.setObjectName("price")
        self.horizontalLayout_7.addWidget(self.price)
        self.horizontalLayout_7.setStretch(1, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.volume = QtWidgets.QSpinBox(self.widget)
        self.volume.setMinimum(1)
        self.volume.setMaximum(9999999)
        self.volume.setObjectName("volume")
        self.horizontalLayout_8.addWidget(self.volume)
        self.horizontalLayout_8.setStretch(1, 9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.buy_btn = QtWidgets.QPushButton(self.widget)
        self.buy_btn.setObjectName("buy_btn")
        self.horizontalLayout_9.addWidget(self.buy_btn)
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setMinimumSize(QtCore.QSize(10, 0))
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_9.addWidget(self.line_5)
        self.short_btn = QtWidgets.QPushButton(self.widget)
        self.short_btn.setObjectName("short_btn")
        self.horizontalLayout_9.addWidget(self.short_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.line_3 = QtWidgets.QFrame(Order)
        self.line_3.setMinimumSize(QtCore.QSize(0, 10))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)

        self.retranslateUi(Order)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Order)

    def retranslateUi(self, Order):
        Order.setWindowTitle(QtWidgets.QApplication.translate("Order", "下单", None, -1))
        self.account_label.setText(QtWidgets.QApplication.translate("Order", "账户信息...", None, -1))
        self.position_table.setSortingEnabled(False)
        self.position_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "持仓合约", None, -1))
        self.position_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "持仓方向", None, -1))
        self.position_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.position_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "持仓手数", None, -1))
        self.position_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "浮动盈亏", None, -1))
        self.position_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "持仓均价", None, -1))
        self.position_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "昨日持仓手数", None, -1))
        self.position_table.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Order", "操作", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.position_tab), QtWidgets.QApplication.translate("Order", "持仓数据", None, -1))
        self.activate_order_table.setSortingEnabled(False)
        self.activate_order_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "id", None, -1))
        self.activate_order_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "报单合约", None, -1))
        self.activate_order_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "报单方向", None, -1))
        self.activate_order_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.activate_order_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "报单手数", None, -1))
        self.activate_order_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "报单价格", None, -1))
        self.activate_order_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "状态", None, -1))
        self.activate_order_table.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Order", "报单时间", None, -1))
        self.activate_order_table.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("Order", "报单类型", None, -1))
        self.activate_order_table.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("Order", "操作", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.active_order_tab), QtWidgets.QApplication.translate("Order", "待成交数据", None, -1))
        self.order_table.setSortingEnabled(False)
        self.order_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "报单合约", None, -1))
        self.order_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "报单方向", None, -1))
        self.order_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.order_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "报单手数", None, -1))
        self.order_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "报单价格", None, -1))
        self.order_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "状态", None, -1))
        self.order_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "时间", None, -1))
        self.order_table.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Order", "价格类型", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.order_tab), QtWidgets.QApplication.translate("Order", "发单数据", None, -1))
        self.trade_table.setSortingEnabled(False)
        self.trade_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Order", "成交合约", None, -1))
        self.trade_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Order", "成交方向", None, -1))
        self.trade_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Order", "交易所", None, -1))
        self.trade_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Order", "报单手数", None, -1))
        self.trade_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Order", "报单价格", None, -1))
        self.trade_table.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Order", "开平", None, -1))
        self.trade_table.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Order", "成交时间", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trade_tab), QtWidgets.QApplication.translate("Order", "成交数据", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Order", "中文名：", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Order", "合约：", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Order", "类型：", None, -1))
        self.price_type.setItemText(0, QtWidgets.QApplication.translate("Order", "限价", None, -1))
        self.price_type.setItemText(1, QtWidgets.QApplication.translate("Order", "市价", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Order", "价格：", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Order", "手数：", None, -1))
        self.buy_btn.setText(QtWidgets.QApplication.translate("Order", "买多", None, -1))
        self.short_btn.setText(QtWidgets.QApplication.translate("Order", "卖空", None, -1))

import app.resource.mainwindow_rc
