# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui',
# licensing of 'signin.ui' applies.
#
# Created: Mon Sep 30 13:58:24 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.setEnabled(True)
        SignIn.resize(1055, 819)
        SignIn.setMinimumSize(QtCore.QSize(1055, 819))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bee/images/bee_temp_grey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignIn.setWindowIcon(icon)
        SignIn.setAutoFillBackground(False)
        self.formLayout_3 = QtWidgets.QFormLayout(SignIn)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(SignIn)
        self.title.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Manjari Thin")
        font.setPointSize(24)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setStyleSheet("color: rgb(32, 74, 135);")
        self.title.setLineWidth(0)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setMargin(5)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.login_tab = QtWidgets.QTabWidget(SignIn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.login_tab.sizePolicy().hasHeightForWidth())
        self.login_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_tab.setFont(font)
        self.login_tab.setStyleSheet("image: url(:/bee/images/bee_temp_grey.png);")
        self.login_tab.setObjectName("login_tab")
        self.login1 = QtWidgets.QWidget()
        self.login1.setObjectName("login1")
        self.gridLayout = QtWidgets.QGridLayout(self.login1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userid_1 = QtWidgets.QLineEdit(self.login1)
        self.userid_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.userid_1.setFont(font)
        self.userid_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.userid_1.setText("")
        self.userid_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userid_1.setObjectName("userid_1")
        self.verticalLayout.addWidget(self.userid_1)
        self.password_1 = QtWidgets.QLineEdit(self.login1)
        self.password_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.password_1.setFont(font)
        self.password_1.setText("")
        self.password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_1.setObjectName("password_1")
        self.verticalLayout.addWidget(self.password_1)
        self.interface_1 = QtWidgets.QComboBox(self.login1)
        self.interface_1.setMinimumSize(QtCore.QSize(200, 0))
        self.interface_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.interface_1.setFont(font)
        self.interface_1.setObjectName("interface_1")
        self.interface_1.addItem("")
        self.interface_1.addItem("")
        self.verticalLayout.addWidget(self.interface_1)
        self.other = QtWidgets.QComboBox(self.login1)
        self.other.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.other.setFont(font)
        self.other.setObjectName("other")
        self.other.addItem("")
        self.other.addItem("")
        self.verticalLayout.addWidget(self.other)
        self.sign_in_btn_1 = QtWidgets.QPushButton(self.login1)
        self.sign_in_btn_1.setEnabled(False)
        self.sign_in_btn_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.sign_in_btn_1.setFont(font)
        self.sign_in_btn_1.setCheckable(False)
        self.sign_in_btn_1.setChecked(False)
        self.sign_in_btn_1.setFlat(False)
        self.sign_in_btn_1.setObjectName("sign_in_btn_1")
        self.verticalLayout.addWidget(self.sign_in_btn_1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.login_tab.addTab(self.login1, "")
        self.login2 = QtWidgets.QWidget()
        self.login2.setObjectName("login2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.login2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userid_2 = QtWidgets.QLineEdit(self.login2)
        self.userid_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.userid_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.userid_2.setFont(font)
        self.userid_2.setObjectName("userid_2")
        self.verticalLayout_2.addWidget(self.userid_2)
        self.password_2 = QtWidgets.QLineEdit(self.login2)
        self.password_2.setEnabled(True)
        self.password_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.password_2.setFont(font)
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.verticalLayout_2.addWidget(self.password_2)
        self.brokerid_2 = QtWidgets.QLineEdit(self.login2)
        self.brokerid_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.brokerid_2.setFont(font)
        self.brokerid_2.setAccessibleName("")
        self.brokerid_2.setAutoFillBackground(False)
        self.brokerid_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.brokerid_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.brokerid_2.setObjectName("brokerid_2")
        self.verticalLayout_2.addWidget(self.brokerid_2)
        self.auth_code_2 = QtWidgets.QLineEdit(self.login2)
        self.auth_code_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.auth_code_2.setFont(font)
        self.auth_code_2.setObjectName("auth_code_2")
        self.verticalLayout_2.addWidget(self.auth_code_2)
        self.appid_2 = QtWidgets.QLineEdit(self.login2)
        self.appid_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.appid_2.setFont(font)
        self.appid_2.setObjectName("appid_2")
        self.verticalLayout_2.addWidget(self.appid_2)
        self.td_address_2 = QtWidgets.QLineEdit(self.login2)
        self.td_address_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.td_address_2.setFont(font)
        self.td_address_2.setObjectName("td_address_2")
        self.verticalLayout_2.addWidget(self.td_address_2)
        self.md_address_2 = QtWidgets.QLineEdit(self.login2)
        self.md_address_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.md_address_2.setFont(font)
        self.md_address_2.setObjectName("md_address_2")
        self.verticalLayout_2.addWidget(self.md_address_2)
        self.interface_2 = QtWidgets.QComboBox(self.login2)
        self.interface_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.interface_2.setFont(font)
        self.interface_2.setObjectName("interface_2")
        self.interface_2.addItem("")
        self.interface_2.addItem("")
        self.verticalLayout_2.addWidget(self.interface_2)
        self.sign_in_btn_2 = QtWidgets.QPushButton(self.login2)
        self.sign_in_btn_2.setEnabled(False)
        self.sign_in_btn_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.sign_in_btn_2.setFont(font)
        self.sign_in_btn_2.setObjectName("sign_in_btn_2")
        self.verticalLayout_2.addWidget(self.sign_in_btn_2)
        self.rember_me = QtWidgets.QCheckBox(self.login2)
        self.rember_me.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rember_me.setFont(font)
        self.rember_me.setChecked(True)
        self.rember_me.setObjectName("rember_me")
        self.verticalLayout_2.addWidget(self.rember_me)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 3, 1, 1)
        self.login_tab.addTab(self.login2, "")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_tab)

        self.retranslateUi(SignIn)
        self.login_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        SignIn.setWindowTitle(QtWidgets.QApplication.translate("SignIn", "Form", None, -1))
        self.title.setText(QtWidgets.QApplication.translate("SignIn", "欢迎使用Ctpbee桌面客户端", None, -1))
        self.userid_1.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "用户名/USERNAME", None, -1))
        self.password_1.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "密码/PASSWORD", None, -1))
        self.interface_1.setItemText(0, QtWidgets.QApplication.translate("SignIn", "ctp", None, -1))
        self.interface_1.setItemText(1, QtWidgets.QApplication.translate("SignIn", "ctp_se", None, -1))
        self.other.setItemText(0, QtWidgets.QApplication.translate("SignIn", "simnow24小时", None, -1))
        self.other.setItemText(1, QtWidgets.QApplication.translate("SignIn", "simnow移动", None, -1))
        self.sign_in_btn_1.setText(QtWidgets.QApplication.translate("SignIn", "登   录", None, -1))
        self.login_tab.setTabText(self.login_tab.indexOf(self.login1), QtWidgets.QApplication.translate("SignIn", "普通登录", None, -1))
        self.userid_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "用户名/USERNAME", None, -1))
        self.password_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "密码/PASSWORD", None, -1))
        self.brokerid_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "期货公司编号/BROKERID", None, -1))
        self.auth_code_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "认证码/AUTH_CODE", None, -1))
        self.appid_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "产品名称/APPID", None, -1))
        self.td_address_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "交易前置/TD_ADDRESS", None, -1))
        self.md_address_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "行情前置/MD_ADDRESS", None, -1))
        self.interface_2.setItemText(0, QtWidgets.QApplication.translate("SignIn", "ctp", None, -1))
        self.interface_2.setItemText(1, QtWidgets.QApplication.translate("SignIn", "ctp_se", None, -1))
        self.sign_in_btn_2.setText(QtWidgets.QApplication.translate("SignIn", "登    录", None, -1))
        self.rember_me.setText(QtWidgets.QApplication.translate("SignIn", "记住我", None, -1))
        self.login_tab.setTabText(self.login_tab.indexOf(self.login2), QtWidgets.QApplication.translate("SignIn", "详细登录", None, -1))

import app.resource.signin_rc
