# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui',
# licensing of 'signin.ui' applies.
#
# Created: Fri Nov 29 13:32:59 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SignIn(object):
    def setupUi(self, SignIn):
        SignIn.setObjectName("SignIn")
        SignIn.setEnabled(True)
        SignIn.resize(315, 405)
        SignIn.setMinimumSize(QtCore.QSize(315, 368))
        SignIn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu/images/bee_temp_grey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignIn.setWindowIcon(icon)
        SignIn.setAutoFillBackground(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SignIn)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QLabel(SignIn)
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.min_btn = QtWidgets.QToolButton(SignIn)
        self.min_btn.setObjectName("min_btn")
        self.horizontalLayout_3.addWidget(self.min_btn)
        self.close_btn = QtWidgets.QToolButton(SignIn)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.login_tab = QtWidgets.QTabWidget(SignIn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.login_tab.sizePolicy().hasHeightForWidth())
        self.login_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_tab.setFont(font)
        self.login_tab.setStyleSheet("")
        self.login_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.login_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.login_tab.setObjectName("login_tab")
        self.login1 = QtWidgets.QWidget()
        self.login1.setObjectName("login1")
        self.formLayout = QtWidgets.QFormLayout(self.login1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.login1)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("image: url(:/menu/images/bee_temp_grey.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.login1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.userid_1 = QtWidgets.QLineEdit(self.login1)
        self.userid_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.userid_1.setFont(font)
        self.userid_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.userid_1.setText("")
        self.userid_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userid_1.setObjectName("userid_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userid_1)
        self.label_3 = QtWidgets.QLabel(self.login1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.password_1 = QtWidgets.QLineEdit(self.login1)
        self.password_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.password_1.setFont(font)
        self.password_1.setText("")
        self.password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_1.setObjectName("password_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_1)
        self.label_4 = QtWidgets.QLabel(self.login1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.interface_1 = QtWidgets.QComboBox(self.login1)
        self.interface_1.setMinimumSize(QtCore.QSize(0, 0))
        self.interface_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.interface_1.setFont(font)
        self.interface_1.setObjectName("interface_1")
        self.interface_1.addItem("")
        self.interface_1.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.interface_1)
        self.label_5 = QtWidgets.QLabel(self.login1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.other = QtWidgets.QComboBox(self.login1)
        self.other.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.other.setFont(font)
        self.other.setObjectName("other")
        self.other.addItem("")
        self.other.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.other)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.sign_in_btn_1 = QtWidgets.QPushButton(self.login1)
        self.sign_in_btn_1.setEnabled(False)
        self.sign_in_btn_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.sign_in_btn_1.setFont(font)
        self.sign_in_btn_1.setCheckable(False)
        self.sign_in_btn_1.setChecked(False)
        self.sign_in_btn_1.setFlat(False)
        self.sign_in_btn_1.setObjectName("sign_in_btn_1")
        self.horizontalLayout_2.addWidget(self.sign_in_btn_1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.login_tab.addTab(self.login1, "")
        self.login2 = QtWidgets.QWidget()
        self.login2.setObjectName("login2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.login2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.userid_2 = QtWidgets.QLineEdit(self.login2)
        self.userid_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.userid_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.userid_2.setFont(font)
        self.userid_2.setObjectName("userid_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userid_2)
        self.label_7 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.password_2 = QtWidgets.QLineEdit(self.login2)
        self.password_2.setEnabled(True)
        self.password_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.password_2.setFont(font)
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_2)
        self.label_8 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.brokerid_2 = QtWidgets.QLineEdit(self.login2)
        self.brokerid_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.brokerid_2.setFont(font)
        self.brokerid_2.setAccessibleName("")
        self.brokerid_2.setAutoFillBackground(False)
        self.brokerid_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.brokerid_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.brokerid_2.setObjectName("brokerid_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.brokerid_2)
        self.label_9 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.auth_code_2 = QtWidgets.QLineEdit(self.login2)
        self.auth_code_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.auth_code_2.setFont(font)
        self.auth_code_2.setObjectName("auth_code_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.auth_code_2)
        self.label_10 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.appid_2 = QtWidgets.QLineEdit(self.login2)
        self.appid_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.appid_2.setFont(font)
        self.appid_2.setObjectName("appid_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.appid_2)
        self.label_11 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.td_address_2 = QtWidgets.QLineEdit(self.login2)
        self.td_address_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.td_address_2.setFont(font)
        self.td_address_2.setObjectName("td_address_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.td_address_2)
        self.label_12 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.md_address_2 = QtWidgets.QLineEdit(self.login2)
        self.md_address_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.md_address_2.setFont(font)
        self.md_address_2.setObjectName("md_address_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.md_address_2)
        self.label_13 = QtWidgets.QLabel(self.login2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.interface_2 = QtWidgets.QComboBox(self.login2)
        self.interface_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.interface_2.setFont(font)
        self.interface_2.setObjectName("interface_2")
        self.interface_2.addItem("")
        self.interface_2.addItem("")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.interface_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.sign_in_btn_2 = QtWidgets.QPushButton(self.login2)
        self.sign_in_btn_2.setEnabled(False)
        self.sign_in_btn_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.sign_in_btn_2.setFont(font)
        self.sign_in_btn_2.setObjectName("sign_in_btn_2")
        self.horizontalLayout.addWidget(self.sign_in_btn_2)
        self.rember_me = QtWidgets.QCheckBox(self.login2)
        self.rember_me.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.rember_me.setFont(font)
        self.rember_me.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rember_me.setChecked(True)
        self.rember_me.setObjectName("rember_me")
        self.horizontalLayout.addWidget(self.rember_me)
        self.formLayout_2.setLayout(9, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.login_tab.addTab(self.login2, "")
        self.verticalLayout_3.addWidget(self.login_tab)

        self.retranslateUi(SignIn)
        self.login_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SignIn)

    def retranslateUi(self, SignIn):
        SignIn.setWindowTitle(QtWidgets.QApplication.translate("SignIn", "Form", None, -1))
        self.title.setText(QtWidgets.QApplication.translate("SignIn", "ctpbee桌面端", None, -1))
        self.min_btn.setText(QtWidgets.QApplication.translate("SignIn", "—", None, -1))
        self.close_btn.setText(QtWidgets.QApplication.translate("SignIn", "×", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("SignIn", "用户名", None, -1))
        self.userid_1.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "USERNAME", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("SignIn", "密  码", None, -1))
        self.password_1.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "PASSWORD", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("SignIn", "接  口", None, -1))
        self.interface_1.setItemText(0, QtWidgets.QApplication.translate("SignIn", "ctp", None, -1))
        self.interface_1.setItemText(1, QtWidgets.QApplication.translate("SignIn", "ctp_se", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("SignIn", "前  置", None, -1))
        self.other.setItemText(0, QtWidgets.QApplication.translate("SignIn", "simnow24小时", None, -1))
        self.other.setItemText(1, QtWidgets.QApplication.translate("SignIn", "simnow移动", None, -1))
        self.sign_in_btn_1.setText(QtWidgets.QApplication.translate("SignIn", "登   录", None, -1))
        self.login_tab.setTabText(self.login_tab.indexOf(self.login1), QtWidgets.QApplication.translate("SignIn", "快速登录", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("SignIn", "用户名", None, -1))
        self.userid_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "USERNAME", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("SignIn", "密码", None, -1))
        self.password_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "PASSWORD", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("SignIn", "期货公司编码", None, -1))
        self.brokerid_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "BROKERID", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("SignIn", "认证码", None, -1))
        self.auth_code_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "AUTH_CODE", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("SignIn", "产品名称", None, -1))
        self.appid_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "APPID", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("SignIn", "交易前置", None, -1))
        self.td_address_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "TD_ADDRESS", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("SignIn", "行情前置", None, -1))
        self.md_address_2.setPlaceholderText(QtWidgets.QApplication.translate("SignIn", "MD_ADDRESS", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("SignIn", "接口", None, -1))
        self.interface_2.setItemText(0, QtWidgets.QApplication.translate("SignIn", "ctp", None, -1))
        self.interface_2.setItemText(1, QtWidgets.QApplication.translate("SignIn", "ctp_se", None, -1))
        self.sign_in_btn_2.setText(QtWidgets.QApplication.translate("SignIn", "登    录", None, -1))
        self.rember_me.setText(QtWidgets.QApplication.translate("SignIn", "记住我", None, -1))
        self.login_tab.setTabText(self.login_tab.indexOf(self.login2), QtWidgets.QApplication.translate("SignIn", "详细登录", None, -1))

import app.resource.mainwindow_rc
